### ISSUE TITLE
interactive_control.py not responding

### ISSUE THREAD

**Issue by techetga** [bskari/pi-rc#13]
Whenever I try to control the car with my arrow keys, the python script doesn't seem to respond. After "Sending commands to 192.168.1.174" it just stops working. Thanks in advance.
![interactive_control py](https://cloud.githubusercontent.com/assets/8191633/7390023/02209306-ee74-11e4-9aa5-a9b3289d1085.png)

**Comment by bskari** [comment]
Oh, the interactive control is a graphical application, so you'll need to either run it from the graphical side of the Raspberry Pi, or locally on another computer. It won't run over SSH.

I should make this clear in the documentation. Sorry for the confusion. If you're running Windows on your main computer, you can install [Python](https://www.python.org/downloads/windows/) and then install the [PyGame](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame) package, and you should be able to run this. I would recommend getting the latest version of Python 3 (looks like that is 3.4.3) and then the version of PyGame that matches. You probably have a 64-bit computer, so get the 64-bit versions.

Let me know if that works.

**Comment by techetga** [comment]
I've a 32-bit Windows 7 PC. I did exactly what you said. I installed Python 3.4.3 with the PyGame package but after the GUI opens, but when I press an arrow key, the GUI closes and I get another error. 
![rc car 2](https://cloud.githubusercontent.com/assets/8191633/7418897/ab1cc918-ef71-11e4-9a41-320cd6114587.png)

So I tried using the WebUI, but I get errors whenever I press on the arrow buttons. (The RC Car responds but doesn't work as normal.
![rc car 3](https://cloud.githubusercontent.com/assets/8191633/7418992/4bd32d48-ef72-11e4-9151-fbe9c7fc9084.png)
Please help

**Comment by bskari** [comment]
Hmm, I *think* I know what is going on with the first problem. I don't have access to a Windows computer to test at the moment, but I can try to test it out tomorrow. I just pushed a potential untested fix, so you can try to pull the latest version and see if you can get the GUI running.

I'm not sure about the second part though... I think it might be related to the web UI which is kind of buggy. If that works though, let me know, and I'll try to figure out what's going on with the web UI. I still have an [issue open](https://github.com/bskari/pi-rc/issues/6) to fix it. If not, I'll have to look more tomorrow.

Thanks for the report!

**Comment by techetga** [comment]
Tried it today, still getting an error.
![interactive_control py2](https://cloud.githubusercontent.com/assets/8191633/7492653/5aa8dafc-f3fa-11e4-8929-1c41a860179f.png)

**Comment by bskari** [comment]
Okay, I was able to reproduce the problem on my Windows Vista machine. It looks like it works with Python 2 and I pushed a fix for Python 3. Do you want to try pulling and testing it again?

**Comment by techetga** [comment]
Thanks, it works now!

**Comment by bskari** [comment]
Great! Glad to hear it; thanks for the detailed report.
